Tuto_Uno/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.iniciovista.as_view(), name='inicio'),
    path('<int:pk>/', views.detallevista.as_view(), name='detalle'),
    path('<int:pk>/resultados/', views.resultadosvista.as_view(), name='resultados'),
    path('<int:pregunta_id>/voto/', views.voto, name='voto'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField('fecha de publicación')
    def __str__(self):
        return self.texto_pregunta
    def fue_publicado_recientemente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.fecha_publicacion <= now
    fue_publicado_recientemente.admin_order_field = 'fecha_publicacion'
    fue_publicado_recientemente.boolean = True
    fue_publicado_recientemente.short_description = '¿Publicado recientemente?'
    


class Eleccion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    texto_eleccion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.texto_eleccion

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Pregunta, Eleccion

class iniciovista(generic.ListView):
    template_name = 'polls/indice.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Devuelva las últimas cinco preguntas publicadas (sin incluir las que se publicarán en el futuro)."""
        return Pregunta.objects.filter(fecha_publicacion__lte=timezone.now()).order_by('-fecha_publicacion')[:5]

class detallevista(generic.DetailView):
    model = Pregunta
    template_name = 'polls/detalle.html'
    def get_queryset(self):
        """
        Excluye cualquier pregunta que aún no se haya publicado.
        """
        return Pregunta.objects.filter(fecha_publicacion__lte=timezone.now())

class resultadosvista(generic.DetailView):
    model = Pregunta
    template_name = 'polls/resultados.html'

def voto(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    try:
        eleccion_elegida = pregunta.eleccion_set.get(pk=request.POST['eleccion'])
    except (KeyError, Eleccion.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detalle.html', {
            'pregunta': pregunta,
            'mensaje_error': "No seleccionaste una opción.",
        })
    else:
        eleccion_elegida.votos += 1
        eleccion_elegida.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:resultados', args=(pregunta.id,)))

polls/templates/polls/detalle.html
<h1>{{ pregunta.texto_pregunta }}</h1>
{% if mensaje_error %}<p><strong>{{ mensaje_error }}</strong></p>{% endif %}

<form action="{% url 'polls:voto' pregunta.id %}" method="POST">
{% csrf_token %}
{% for eleccion in pregunta.eleccion_set.all %}
    <input type="radio" name="eleccion" id="eleccion{{ forloop.counter }}" value="{{ eleccion.id }}">
    <label for="eleccion{{ forloop.counter }}">{{ eleccion.texto_eleccion }}</label><br>
{% endfor %}
<input type="submit" value="voto">
</form>

<!--<ul>
{% for eleccion in Pregunta.conjunto_eleccion.all %}
    <li>{{ eleccion.texto_eleccion }}</li>
{% endfor %}
</ul>
-->

polls/templates/polls/indice.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for Pregunta in latest_question_list %}
        <li>
            <!-- <a href="/polls/{{ Pregunta.id }}/">{{ Pregunta.texto_pregunta }}</a> -->
            <a href="{% url 'polls:detalle' Pregunta.id %}">{{ Pregunta.texto_pregunta }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas disponibles.</p>
{% endif %}

polls/templates/polls/resultados.html
<h1>{{ Pregunta.texto_pregunta }}</h1>

<ul>
    {% for eleccion in pregunta.eleccion_set.all %}
        <li>{{ eleccion.texto_eleccion }} -- {{ eleccion.votos }} voto {{ eleccion.votos|pluralize }}</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detalle' pregunta.id %}">Vota de nuevo?</a>